apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: wapp-sidekiq
        imagePullPolicy: Never
        env:
          - name: OPEN_WEATHER_API_KEY
            valueFrom:
              configMapKeyRef:
                name: weather-app-config
                key: OPEN_WEATHER_API_KEY
